name: Terraform sqs
on:
  workflow_dispatch:
  push:
    branches:
      - '*'
  pull_request:
    types:
      - opened
    branches:
      - 'main'

jobs:
  release_terraform:
    name: Terraform SQS Job
    runs-on: ubuntu-latest
    steps:
      - uses: hashicorp/setup-terraform@v3
      
      - name: Change to working directory
        run: cd ..

      - name: Terraform fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Config
        run: git config --global init.defaultBranch main

      - name: Terraform Init
        run: terraform init -backend-config=backend.conf
        env:
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN:  ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Terraform Validate
        run: terraform validate -no-color
      
      - name: Terraform Apply
        run: terraform apply -auto-approve -no-color
        env:
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN:  ${{ secrets.AWS_SESSION_TOKEN }}
